(cl:in-package #:clcl-tests)
(in-suite* unification)

(defvar *env*)

(defmacro with-ocl-env (&body body)
  `(let ((*env* (ocl-env (fset:empty-map)
                         (fset:empty-map))))
     ,@body))

(defun unify (place expr)
  (unify-types place expr (unified '() '() '() *env*)))

(defun print-id (x)
  (write x :pretty nil)
  (terpri)
  x)

(defun unify-success (place expr)
  (fresh-line)
  (write 'unifying-and-expecting-success)
  (terpri)
  (write place)
  (terpri)
  (write expr)
  (terpri)
  (is (typep (print-id (unify place expr)) 'unified)))

(defun unify-failure (place expr)
  (fresh-line)
  (write 'unifying-and-expecting-failure)
  (terpri)
  (write place)
  (terpri)
  (write expr)
  (terpri)
  (is (typep (print-id (unify place expr)) 'unify-error)))

(defun unify-loop (place expr)
  (fresh-line)
  (write 'unifying-and-expecting-occurs-check)
  (terpri)
  (write place)
  (terpri)
  (write expr)
  (terpri)
  (is (typep (print-id (unify place expr)) 'occurs-check)))

(defun name (name)
  (make-instance 'simple-name :counter 0 :name name))

(defun var (symbol)
  (make-instance 'variable-type :counter 0 :name (name symbol)))

(test simple
  (with-ocl-env
    (unify-success (var 'foo) (dimension 42 (name 'array-rank)))
   (unify-success (var 'foo) (var 'foo))
   (unify-failure (dimension 42 (name 'array-rank)) (var 'foo))
   (let* ((foo (function-type (list (name 'foo)
                                    (name 'bar))
                              (list (var 'foo)
                                    (var 'bar))
                              (name 'foo)))
          (bar (function-type (list (name 'xenu))
                              (list foo)
                              (name 'bar))))
     (unify-failure foo bar)
     (unify-failure bar foo)
     (unify-success bar bar))
   (let* ((foo (function-type (list (name 'foo))
                              (list (function-type (list (name 'foo))
                                                   (list (var 'xenu))
                                                   (name 'h)))
                              (name 'f)))
          (bar (function-type (list (name 'bar))
                              (list foo)
                              (name 'g))))
     (unify-success foo bar)
     (unify-failure bar foo))))

(test cycles
  (with-ocl-env
    (let* ((bar (function-type '() '() (name 'cyclic))))
      (reinitialize-instance bar :member-types (list bar) :member-names (list (name 'cycles-r-us)))
      (unify-loop bar bar))))

(run!)
